config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :letters, param: :token
  end

  scope "/:locale" do
    resources :letters, param: :slug do
      collection do
        get "upload"
      end
      member do
        get "thanks"
      end
    end

    get 'about', to: 'statics#about'
    get 'faq', to: 'statics#faq'
    get 'privacy', to: 'statics#privacy'
    get 'terms', to: 'statics#terms'
    get 'partners', to: 'statics#partners'

  end


  get "/:locale", to: redirect('/%{locale}/letters/new')
  root to: redirect('/en/letters/new')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/letter.rb
class Letter < ApplicationRecord
  has_rich_text :body
  has_one_attached :user_upload
  has_one_attached :reviewed_pdf

  before_create :set_secure_tokens
  enum status: [ :draft, :submitted, :accepted, :declined ]

  def self.published(filter_langs)
    scope = self.accepted.where("catalog = true")
    return scope unless filter_langs.present?
    scope.where(lang: filter_langs)
  end

  def next(filter_langs)
    return if private?
    Letter.published(filter_langs).where("id > ?", id).order("id ASC").first
  end

  def prev(filter_langs)
    return if private?
    Letter.published(filter_langs).where("id < ?", id).order("id DESC").first
  end

  def to_param
    self.slug
  end

  def private?
    self.catalog? && self.submitted?
  end

  def display_name
    s = "#%04d" % id
    return s unless self.publish_name?
    s + ": " + name
  end

  private

  def set_secure_tokens
    loop do
      self.slug = SecureRandom.uuid
      break unless Letter.where(slug: slug).exists?
    end
    loop do
      self.token = SecureRandom.uuid
      break unless Letter.where(slug: token).exists?
    end
  end

end

app/controllers/admin/letters_controller.rb
module Admin
  class LettersController < ApplicationController
    before_action :set_letter, only: [:edit, :update]

    # do not enter an unprotected action here like #index
    # it would display all, also private letters without permission
    # checks
    def index
      raise "not allowed error"
    end

    def edit
    end

    def update
      @letter.update!(letter_params)
      redirect_to edit_admin_letter_url(@letter.token)
    end

    private

    # for admins letters are gathered by a secret token, not the public
    # uuid
    def set_letter
      @letter = Letter.find_by_token(params[:token])
    end

    def letter_params
      params.require(:letter).permit(:body, :name, :email, :age, :canton, :lang, :publish_name, :publish_age, :publish_canton, :terms, :privacy, :over_15, :newsletter, :user_upload, :status, :reviewed_pdf)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end

end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show, :edit, :update, :destroy, :thanks]
  before_action :set_nav_write, only: [:new, :edit, :thanks]
  before_action :set_nav_letters, only: [:index, :show]

  def index
    @filter_langs = params[:filter_langs] || []
    @letters = Letter.published(@filter_langs).with_rich_text_body.with_attached_reviewed_pdf.order("id DESC").limit(100)
  end

  def show
    @filter_langs = params[:filter_langs]
    @prev = @letter.prev(@filter_langs)
    @next = @letter.next(@filter_langs)
  end


  def new
    @letter = Letter.new
    @feed_images = (1..16).to_a.shuffle.first(9).map { |i| "feed#{i}.jpg" }
  end


  def edit
  end

  def upload
    @nav = :upload
    @letter = Letter.new
    @letter.lang = I18n.locale
    @letter.catalog = true
  end


  def create
    @letter = Letter.new(letter_params)
    @letter.catalog ||= true

    # letter came via online form - personal data needed
    if @letter.body.present?
      @letter.lang ||= I18n.locale
      @letter.status = :draft
      @letter.save!
      return redirect_to edit_letter_url(@letter)
    end
    # letter came via upload - all data present
    if @letter.user_upload.present?
      @letter.status = :submitted
      @letter.save!
      ApplicationMailer.send_notifications(@letter)
      return redirect_to thanks_letter_url(@letter)
    end
    # corner case, e.g. empty letter submitted
    return redirect_to new_letter_url
  end


  def update
    @letter.status = :submitted

    respond_to do |format|
      if @letter.update(letter_params)
        ApplicationMailer.send_notifications(@letter)
        format.html { redirect_to thanks_letter_url(@letter) }
        format.json { render :show, status: :ok, location: @letter }
      else
        format.html { render :edit }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  def thanks

  end

  def destroy
    @letter.destroy
    respond_to do |format|
      format.html { redirect_to letters_url, notice: 'Letter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.find_by_slug(params[:slug])
    end

    # Only allow a list of trusted parameters through.
    def letter_params
      # make sure not to include here:
      # - status
      # - slug
      # - token
      # - id
      params.require(:letter).permit(:body, :name, :email, :age, :canton, :lang, :publish_name, :publish_age, :publish_canton, :terms, :privacy, :over_15, :newsletter, :user_upload)
    end

    def set_nav_write
      @nav = :write
    end

    def set_nav_letters
      @nav = :letters
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def about
    @nav = :about
  end

  def faq
    @nav = :faq
  end

  def privacy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def options_for_lang
    I18n.available_locales.map do |locale|
      [t(locale, scope: :locales), locale]
    end
  end

  def options_for_canton(canton)
    cantons = [
        ["Zürich", "ZH"],
        ["Bern / Berne", "BE"],
        ["Luzern", "LU"],
        ["Uri", "UR"],
        ["Schwyz", "SZ"],
        ["Obwalden", "OW"],
        ["Nidwalden", "NW"],
        ["Glarus", "GL"],
        ["Zug", "ZG"],
        ["Freiburg / Fribourg", "FR"],
        ["Solothurn", "SO"],
        ["Basel Stadt", "BS"],
        ["Basel Land", "BL"],
        ["Schaffhausen", "SH"],
        ["Appenzell Ausserrhoden", "AR"],
        ["Appenzell Innerrhoden", "AI"],
        ["Sankt Gallen", "SG"],
        ["Graubünden", "GR"],
        ["Aargau", "AG"],
        ["Thurgau", "TG"],
        ["Ticino", "TI"],
        ["Vaud", "VD"],
        ["Valais / Wallis", "VS"],
        ["Neuchâtel", "NE"],
        ["Genève", "GE"],
        ["Jura", "JU"],
    ].sort_by(&:first)
    cantons.append [t("canton.abroad"), :abroad]
    cantons.append [t("canton.other"), :other]
    cantons.insert(0, [t("letters.edit.placeholder_canton"),"", disabled: true, selected: canton.blank?])
  end

  VARIANTS = {
      thumbnail: "440x622",
      gallery: "824"
  }.freeze

  def og_image(letter)
    if (letter.reviewed_pdf.present? && letter.reviewed_pdf.previewable?)
      return url_for(letter.reviewed_pdf.preview(resize: VARIANTS[:thumbnail]))
    else
      return image_url("instagram.#{@letter.lang}.png")
    end
  end

  def letter_preview(letter, variant)
    return unless letter.reviewed_pdf.present?
    return unless letter.reviewed_pdf.previewable?
    return image_tag letter.reviewed_pdf.preview(resize: VARIANTS[variant])
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/letters/edit.html.erb
<% if @letter.body.present? %>
  <%= render "/letters/show" %>
<% end %>

<%= form_with(model: @letter, url: admin_letter_path(@letter.token), local: true, class: "pt-2 pb-2") do |form| %>

  <fieldset id="admin">
    <% if @letter.user_upload.present? %>
      <p>User uploaded letter:</p>
      <a class="button" href="<%= rails_blob_path(@letter.user_upload, disposition: "attachment") %>">
        Download original letter
      </a>

      <hr>

      <p class="mt-2">Reviewed letter (Please use PDF only in A4 format):</p>
      <% if @letter.reviewed_pdf.present? %>
        <a class="button" href="<%= rails_blob_path(@letter.reviewed_pdf, disposition: "attachment") %>">
          Download reviewed pdf
        </a>
        <%= letter_preview(@letter, :thumbnail) %>
  <% end %>
      <%= form.file_field :reviewed_pdf %>
  <% end %>

    <hr>
    <p class="mt-2">Only letters with state "accepted" are show on the website:</p>
    <%= form.select :status, Letter.statuses.keys %>

    <%= submit_tag "Save changes", class: "mt-2 mb-2" %>

  </fieldset>

  <%= render "/letters/personal_form", form: form %>

<% end %>

app/views/layouts/_seo.de.html.erb
<title>LiäbiSchweiz - schreib einen Brief an die Zukunft der Schweiz.</title>
<meta name="Description" CONTENT="Liäbi Schweiz ist eine initiative, welche es Menschen mit einem Bezug zur Schweiz möglich macht, einen Brief an die Zukunft der Schweiz zu schreiben.">
<meta property="og:title" content="Liäbi Schweiz" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://www.dearswitzerland.org/de/" />
<meta property="og:image" content="<%= image_url('logo.png') %>" />
<meta property="og:description" content="Liäbi Schweiz - schreib einen Brief an die Zukunft der Schweiz." />
<meta property="og:site_name" content="Liäbi Schweiz" />

app/views/layouts/_seo.en.html.erb
<title>Dear Switzerland - a venue to write a letter to Switzerland's future.</title>
<meta name="Description" CONTENT="Dear Switzerland is a letter-writing initiative, inviting people with a Swiss connection to write to the country’s future.">
<meta property="og:title" content="Dear Switzerland" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://dearswitzerland.org" />
<meta property="og:image" content="<%= image_url('logo.png') %>" />
<meta property="og:description" content="Dear Switzerland - a venue to write a letter to Switzerland's future." />
<meta property="og:site_name" content="Dear Switzerland" />

app/views/layouts/_seo.fr.html.erb
<title>Chère suisse - une plateforme pour rédiger une lettre à la Suisse future.</title>
<meta name="Description" CONTENT="Chère Suisse est une initiative, qui invite les personnes ayant un lien avec la Suisse à écrire un lettre sur l'avenir du pays.">
<meta property="og:title" content="Chère Suisse " />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://dearswitzerland.org/fr/" />
<meta property="og:image" content="<%= image_url('logo.png') %>" />
<meta property="og:description" content="Chère Suisse - une plateforme pour rédiger une lettre à la Suisse future." />
<meta property="og:site_name" content="Chère Suisse" />

app/views/layouts/_seo.it.html.erb
<title>Cara Svizzera - una piattaforma per scrivere una lattera al futuro della Svizzera.</title>
<meta name="Description" CONTENT="Cara Svizzera è un'iniziativa, che invita tutte le persone che hanno un legamo con la Svizzera, a scrivere una lettera sul futuro del paese.">
<meta property="og:title" content="Cara Svizzera" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://dearswitzerland.org/it/" />
<meta property="og:image" content="<%= image_url('logo.png') %>" />
<meta property="og:description" content="Cara Svizzera - una piattaforma per scrivere una lattera al futuro della Svizzera." />
<meta property="og:site_name" content="Cara Svizzera" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <% if content_for?(:seo) %>
    <%= yield(:seo) %>
  <% else %>
    <%= render partial: "/layouts/seo" %>
  <% end %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0,user-scalable=0">

  <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;700&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
  <link rel="manifest" href="/site.webmanifest">
</head>

<body class="<%= controller.controller_name+' '+controller.action_name%>">

<header class="pt-1" data-controller="menu">
  <div class="control mobile" data-action="click->menu#open">
    <%= image_tag "menu-1.svg" %>
  </div>
  <nav class="desktop" data-target="menu.nav">
    <div class="control mobile" data-action="click->menu#close">
      <%= image_tag "menu-2.svg" %>
    </div>
    <ul>
      <li class="<%= "active" if :write == @nav %>">
        <%= link_to t("nav.new_letter_path"), new_letter_path %>
      </li>
      <li class="<%= "active" if :upload == @nav %>">
        <%= link_to t("nav.upload_letter_path"), upload_letters_path %>
      </li>
      <li class="<%= "active" if :letters == @nav %>">
        <%= link_to t("nav.letters_path"), letters_path %>
      </li>
      <li class="<%= "active" if :about == @nav %>">
        <%= link_to t("nav.about_path"), about_path %>
      </li>
      <li class="<%= "active" if :partners == @nav %>">
        <%= link_to t("nav.partners_path"), partners_path %>
      </li>
      <li class="<%= "active" if :faq == @nav %>">
        <%= link_to t("nav.faq_path"), faq_path %>
      </li>
      <li class="mobile">
        <a href="https://www.facebook.com/Dear-Switzerland-103540081329743" target="_blank" class="icon">
          <%= image_tag "facebook-light.svg" %>
        </a>
      </li>
      <li class="mobile">
        <a href="https://instagram.com/dear.switzerland" target="_blank" class="icon">
          <%= image_tag "instagram-light.svg" %>
        </a>
      </li>
      <li class="mobile">
        <a href="https://linkedin.com/company/dearswitzerland" target="_blank" class="icon">
          <%= image_tag "linkedin-light.svg" %>
        </a>
      </li>
    </ul>

    <ul id="locales">
      <% I18n.available_locales.each do |locale| %>
        <li class="<%= "active" if I18n.locale == locale %>">
          <%= link_to locale.to_s.upcase, locale: locale %>
        </li>
      <% end %>
    </ul>
  </nav>

  <nav class="desktop" data-target="menu.nav">
    <ul>
      <li>
        <a href="https://www.facebook.com/Dear-Switzerland-103540081329743" target="_blank" class="icon">
          <%= image_tag "facebook-light.svg" %>
        </a>
      </li>
      <li>
        <a href="https://instagram.com/dear.switzerland" target="_blank" class="icon">
          <%= image_tag "instagram-light.svg" %>
        </a>
      </li>
      <li>
        <a href="https://linkedin.com/company/dearswitzerland" target="_blank" class="icon">
          <%= image_tag "linkedin-light.svg" %>
        </a>
      </li>
    </ul>
  </nav>
</header>

<main>
  <%= yield %>
</main>

<a href="<%= new_letter_path %>" id="logo">
<%= image_tag "logo.svg" %>
</a>

<footer class="pt-5 pb-2" data-action="click->application#logoclick">
  <p class="mt-2 mb-2"><%= t("footer.versusvirus") %></p>
  <p  class="mt-2 mb-2 partners">
    <a href="https://www.versusvirus.ch/" target="_blank" class="partner">
      <%= image_tag "versusvirus.png" %>
    </a>
    <a href="https://ec-epfl.ch/" target="_blank" class="partner">
      <%= image_tag "ec.png" %>
    </a>
  </p>
  <a href="https://www.facebook.com/Dear-Switzerland-103540081329743" target="_blank" class="icon">
    <%= image_tag "facebook-light.svg" %>
  </a>
  <a href="https://instagram.com/dear.switzerland" target="_blank" class="icon">
    <%= image_tag "instagram-light.svg" %>
  </a>
  <a href="https://linkedin.com/company/dearswitzerland" target="_blank" class="icon">
    <%= image_tag "linkedin-light.svg" %>
  </a>
  <address class="mt-2">
    <%= t("footer.address1") %><br>
    <%= t("footer.address2") %><br>
  </address>
  <p><%= mail_to "info@dearswitzerland.org" %></p>
  <p class="mt-2 mb-2">
    <%= link_to t("footer.privacy"), privacy_path %> |
    <%= link_to t("footer.terms"), terms_path %>
  </p>
</footer>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-163371515-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-163371515-1');
</script>

</body>

</html>

app/views/letters/_personal_form.html.erb
<fieldset id="personal">
  <%= form.text_field :name, placeholder: t("letters.edit.placeholder_name") %>
  <%= form.check_box :publish_name %>
  <%= form.label :publish_name, t("letters.edit.label_publish_name") %>
  <%= form.email_field :email, placeholder: t("letters.edit.placeholder_email"), required: true %>
  <%= form.label :email, t("letters.edit.label_email") %>
  <%= form.number_field :age, placeholder: t("letters.edit.placeholder_age") %>
  <%= form.check_box :publish_age %>
  <%= form.label :publish_age, t("letters.edit.label_publish_age") %>
  <%= form.select :canton, options_for_canton(@letter.canton) %>
  <%= form.check_box :publish_canton %>
  <%= form.label :publish_canton, t("letters.edit.label_publish_canton") %>
  <%= form.select :lang, options_for_lang %>
  <p class="pt-1"><%= t("letters.edit.required") %></p>
</fieldset>
<fieldset id="consent" class="mt-2">
  <h3><%= t("letters.edit.legend_consent") %></h3>
  <div class="field">
    <%= form.check_box :terms %>
    <%= form.label :terms, t("letters.edit.label_terms_html") %>
  </div>
  <div class="field">
    <%= form.check_box :privacy %>
    <%= form.label :privacy, t("letters.edit.label_privacy_html") %>
  </div>
  <div class="field">
    <%= form.check_box :over_15 %>
    <%= form.label :over_15, t("letters.edit.label_over_15") %>
  </div>
  <div class="field">
    <%= form.check_box :newsletter %>
    <%= form.label :newsletter, t("letters.edit.label_newsletter") %>
  </div>

  <%= submit_tag t("letters.edit.submit"), class: "mt-3" %>

</fieldset>



app/views/letters/_show.html.erb
<div class="letter">
  <% if @letter.body.present? %>
    <%= @letter.body %>
  <% end %>
  <% if @letter.reviewed_pdf.present? %>
    <%= letter_preview(@letter, :gallery) %>
  <% end %>
</div>


app/views/letters/edit.html.erb
<h1 class="mt-2 mb-2">
<%= t("letters.edit.title1") %>
  <strong><%= t("letters.edit.title2") %></strong>
</h1>

<p><%= t("letters.edit.hint") %></p>

<%= form_with(model: @letter, local: true, class: "pt-2 pb-2") do |form| %>

  <%= render "personal_form", form: form %>

<% end %>

app/views/letters/index.html.erb
<h1 class="mt-2 mb-2">
<%= t("letters.index.title1") %>
  <strong><%= t("letters.index.title2") %></strong>
</h1>

<p><%= t("letters.index.hint") %></p>

<div class="thumbnails mt-2" data-controller="thumbnails">

  <p><%= t("letters.index.filter") %></p>

  <ul class="filter_langs mb-2">
    <% I18n.available_locales.map(&:to_s).each do |lang| %>
      <li>
        <label>
          <%= check_box_tag "filter_langs[]", lang, @filter_langs.include?(lang), data: { action: "change->thumbnails#filter", target: "thumbnails.filterLang" } %>
          <%= t(lang, scope: :locales) %>
        </label>
      </li>
    <% end %>
  </ul>

  <% @letters.each do |letter| %>
    <div class="thumbnail" data-action="click->thumbnails#open">
      <div class="letter">
        <% if letter.body.present? %>
          <%= letter.body %>
        <% end %>
        <% if letter.user_upload.present? %>
          <%= letter_preview(letter, :thumbnail) %>
        <% end %>
      </div>
      <%= link_to letter.display_name, letter_path(letter, filter_langs: @filter_langs) %>
    </div>
  <% end %>
</div>

app/views/letters/new.html.erb
<h1 class="mt-2 mb-2">
  <%= t("letters.new.title1") %>
  <strong><%= t("letters.new.title2") %></strong>
</h1>


<div class="questions">
  <p>
    <%= t("letters.new.question1") %><br>
    <%= t("letters.new.question2") %><br>
    <%= t("letters.new.question3") %>
  </p>
</div>


<h2 class="mb-3">
  <%= t("letters.new.subtitle") %>
</h2>

<p class="mb-3">
  <%= t("letters.new.intro") %><br>
</p>

<%= form_with(model: @letter, local: true) do |form| %>
  <div class="trix">
    <p class="greeting"><%= t('letters.new.greeting') %></p>
    <%= form.rich_text_area :body, placeholder: t('letters.new.placeholder') %>
    <%= submit_tag t("letters.edit.submit"), class: "mt-2" %>
  </div>
<% end %>


<div class="offline mt-3">
  <p><%= t("letters.new.offline1") %></p>
  <p>
    <a href="/letter.<%= I18n.locale %>.pdf" class="button">
      <%= t("letters.new.offline2") %>
    </a>
    </a>
  </p>
</div>

<h3 class='mt-10 mb-1'>Instagram</h3>
<div class="feed mb-10">
  <% @feed_images.each do |img| %>
    <div class="item">
      <%= image_tag img %>
    </div>
  <% end %>
</div>

app/views/letters/show.html.erb
<% content_for :seo do %>
  <title>Dear Switzerland - Letter <%= @letter.display_name %></title>
  <meta name="Description" CONTENT="Letter <%= @letter.display_name %> to Switzerland's future ">
  <meta property="og:title" content="Dear Switzerland - <%= @letter.display_name %>"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="<%= request.original_url %>"/>
  <meta property="og:image" content="<%= og_image(@letter) %>"/>
  <meta property="og:description" content="Dear Switzerland - a venue to write a letter to Switzerland's future."/>
  <meta property="og:site_name" content="Dear Switzerland"/>
<% end %>

<div class="gallery mt-2">

  <%= render "show" %>

  <% if @prev %>
    <nav id="prev">
      <%= link_to image_tag("right.svg"), letter_path(@prev, filter_langs: @filter_langs) %>
    </nav>
  <% end %>

  <% if @next %>
    <nav id="next">
      <%= link_to image_tag("left.svg"), letter_path(@next, filter_langs: @filter_langs) %>
    </nav>
  <% end %>

  <p class="mt-1"><%= @letter.display_name %></p>
  <% if @letter.private? %>
    <p class="mt-1"><%= t("letters.show.private") %></p>
  <% end %>

  <% if @letter.reviewed_pdf.present? %>
    <a class="button" href="<%= rails_blob_path(@letter.reviewed_pdf, disposition: "attachment") %>">
      Download full letter as PDF
    </a>
  <% end %>

  <%= link_to t('letters.show.back'), letters_path %>

  <div class="share mt-1 mb-3">
    <a href="https://www.facebook.com/sharer/sharer.php?u=<%= url_encode(request.original_url) %>" target="_blank">
      <%= image_tag "facebook.svg" %>
    </a>
    <a href="https://twitter.com/share?url=<%= url_encode(request.original_url) %>" target="_blank">
      <%= image_tag "twitter.svg" %>
    </a>
    <a href="https://www.linkedin.com/shareArticle?mini=true&url=<%= url_encode(request.original_url) %>" target="_blank">
      <%= image_tag "linkedin.svg" %>
    </a>
  </div>


</div>

app/views/letters/thanks.html.erb
<h1 class="mt-2 mb-2">
<%= t("letters.thanks.title1") %>
  <strong><%= t("letters.thanks.title2") %></strong>
</h1>

<h2 class="mb-2"><%= t("letters.thanks.subtitle") %></h2>

<p><%= t("letters.thanks.p1") %></p>
<p><%= t("letters.thanks.p2") %> <%=mail_to("info@dearswitzerland.org") %></p>

app/views/letters/upload.html.erb
<h1 class="mt-2 mb-2">
<%= t("letters.upload.title1") %>
  <strong><%= t("letters.upload.title2") %></strong>
</h1>

<p><%= t("letters.edit.hint") %></p>

<%= form_with(model: @letter, local: true, class: "pt-2 pb-2") do |form| %>

  <fieldset id="upload" data-controller="upload">
    <div class="upload-btn-wrapper">
      <button class="btn">
          <span data-target="upload.nofile" class="button">
            <%= t("letters.upload.nofile") %>
          </span>
        <span data-target="upload.hasfile" style="display: none;">
            <%= t("letters.upload.hasfile") %>
          </span>
      </button>
      <%= form.file_field :user_upload, data: {action: "change->upload#upload"} %>
    </div>
  </fieldset>

  <%= render "personal_form", form: form %>


<% end %>

app/views/statics/partners.de.html.erb
<h1 class="mt-3 mb-3">
  unsere
  <strong>Partner und Unterstützer</strong>
</h1>

<section class="pt-1 pb-2">
  <p>
    Als eine informelle Gruppe von Freiwilligen sind wir äusserst dankbar für die wertvolle Unterstützung so vieler Menschen und Organisationen, darunter:
  </p>
</section>

<%= render 'partners' %>

app/views/statics/partners.en.html.erb
<h1 class="mt-3 mb-3">
  our
  <strong>Partners and Supporters </strong>
</h1>

<section class="pt-1 pb-2">
  <p>
    As an informal group of volunteers, we are extremely grateful for the valuable support of so many people and organizations, including:
  </p>
</section>

<%= render partial: 'partners' %>

app/views/statics/partners.fr.html.erb
<h1 class="mt-3 mb-3">
  nos
  <strong>Partenaires et Supporters</strong>
</h1>

<section class="pt-1 pb-2">
  <p>
    En tant que groupe informel de bénévoles, nous sommes extrêmement reconnaissants du précieux soutien de tant de personnes et d'organisations, notamment:
  </p>
</section>

<%= render partial: 'partners' %>